### ISSUE TITLE
Couldn't load plugin 'ParamHist' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by sivansakthi** [millsapjohn/qgis_paramhist#1]
Couldn't load plugin 'ParamHist' due to an error when calling its classFactory() method 

IndexError: child index out of range 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~4.3/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sivansakthi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ParamHist\__init__.py", line 4, in classFactory
    return ParamHistPlugin(iface)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sivansakthi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ParamHist\paramhist.py", line 18, in __init__
    self.parsed_history = parseHistory(self.raw_history)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sivansakthi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ParamHist\hist_connect.py", line 94, in parseHistory
    for child in root[2][3]:
                 ~~~~~~~^^^
IndexError: child index out of range

**Comment by millsapjohn** [comment]
Thanks for posting. Does the file "C:\Users\sivansakthi\AppData\Roaming\QGIS\QGIS3\profiles\default\user-history.db" exist on your machine? If so, could you attach that file so I can take a look?

**Comment by sivansakthi** [comment]
[user-history.zip](https://github.com/user-attachments/files/17469380/user-history.zip)
Here is the file

**Comment by millsapjohn** [comment]
fixed in #c12a400 - you should see the update in the Plugin Manager in a day or two.

**Comment by sivansakthi** [comment]
Thanks for the quick reply.
